### PR TITLE
Address review comments

### PR DESCRIPTION
**Pull request by Wollac**

### CODE REVIEW

**Review by GalRogozinski — COMMENTED** [review]
I am still just wondering whether the possible effect on a 2nd layer shouldn't be added here..
If not here I believe it should be mentioned somewhere (I just don't know where)

Other than that I am good with merging

**Comment by Wollac** [comment]
What effects do you mean?

**Comment by GalRogozinski** [comment]
Imagine some second layer holding a commitment transaction that was never transmitted to the tangle, but is known to second layer participants.

Participants in the second layer want to monitor when this transaction is committed to the tangle so they could act accordingly.
If they do so by monitoring for the entire message hash they are susceptible to signature malleability attacks (including attacks that involve the holder of the secret key).

If they are aware of the issue they can circumvent the problem by checking the transaction essence hash instead and doing a signature validation test for example...
I don't know if there will ever be a second layer for Iota where this will become an issue, and I guess most common use cases involve a multisig (that we currently don't support).

However, this is an issue for other cryptos.
I guess the lightning network in bitcoin is the most famous case.

**Comment by Wollac** [comment]
You've explicitly mentioned the Lightning network under `' Motivation` (and this is still in there).
Does this not address exactly this? You would want to add more? Or change that?

**Comment by GalRogozinski** [comment]
I thought you deleted it but I see it is still there now

**Review by GalRogozinski — APPROVED** [review]

**Pull request merged**
